[formatting]
align_comments = false
allowed_blank_lines = 1
column_width = 100
reorder_arrays = true
reorder_inline_tables = true
reorder_keys = true

[[rule]]
include = ["**/aerospace.toml"]
[rule.formatting]
reorder_arrays = false # Config file is sensitive to array order
