config-version = 2

start-at-login = true

accordion-padding = 150
persistent-workspaces = ["1", "2", "3", "4"] # A 5th workspace is added when using a second display

[gaps]
inner.horizontal = 20
inner.vertical = 20
outer.bottom = 30
outer.left = 40
outer.right = 40
outer.top = 30

[mode.main.binding]

cmd-alt-ctrl-h = 'focus left'
cmd-alt-ctrl-j = 'focus down'
cmd-alt-ctrl-k = 'focus up'
cmd-alt-ctrl-l = 'focus right'
cmd-alt-ctrl-shift-h = 'move left'
cmd-alt-ctrl-shift-j = 'move down'
cmd-alt-ctrl-shift-k = 'move up'
cmd-alt-ctrl-shift-l = 'move right'

cmd-alt-ctrl-n = 'workspace next'
cmd-alt-ctrl-p = 'workspace prev'
cmd-alt-ctrl-shift-n = ['move-node-to-workspace next', 'workspace next']
cmd-alt-ctrl-shift-p = ['move-node-to-workspace prev', 'workspace prev']

cmd-alt-ctrl-1 = 'workspace 1'
cmd-alt-ctrl-2 = 'workspace 2'
cmd-alt-ctrl-3 = 'workspace 3'
cmd-alt-ctrl-4 = 'workspace 4'
cmd-alt-ctrl-5 = 'workspace 5'
cmd-alt-ctrl-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-alt-ctrl-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-alt-ctrl-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-alt-ctrl-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-alt-ctrl-shift-5 = ['move-node-to-workspace 5', 'workspace 5']

# Mnemonic: form some kind of arrow block, a bit similar to Vim's hjkl
cmd-alt-ctrl-backslash = 'join-with up'
cmd-alt-ctrl-leftSquareBracket = 'join-with left'
cmd-alt-ctrl-quote = 'join-with down'
cmd-alt-ctrl-rightSquareBracket = 'join-with right'

cmd-alt-ctrl-f = 'layout floating tiling' # Toggle floating
cmd-alt-ctrl-o = 'workspace-back-and-forth' # Like Vim/Neovim's <C-o>
cmd-alt-ctrl-r = 'flatten-workspace-tree' # Reset joins
cmd-alt-ctrl-z = 'fullscreen' # Toggle zoom

cmd-alt-ctrl-equal = 'resize smart +50'
cmd-alt-ctrl-minus = 'resize smart -50'

cmd-alt-ctrl-b = 'exec-and-forget open -a Zen' # Like "browser"
cmd-alt-ctrl-m = 'exec-and-forget open -a Slack' # Like "messages" 
cmd-alt-ctrl-s = 'exec-and-forget open -a Spotify' # Like "songs"
cmd-alt-ctrl-t = 'exec-and-forget open -a WezTerm' # Like "terminal"

cmd-alt-ctrl-space = 'mode service'

[mode.service.binding]

l = ['layout tiles accordion', 'mode main'] # Change layout
o = ['layout horizontal vertical', 'mode main'] # Change orientation

d = ['enable off'] # Disable AeroSpace 
r = ['reload-config', 'mode main'] # Reload AeroSpace config

esc = ['mode main']

[[on-window-detected]]
if.app-name-regex-substring = 'Finder|Preview|System Settings|Archive Utility'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Slack|Spotify'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Zen'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'WezTerm'
run = 'move-node-to-workspace 3'

[[on-window-detected]] # Last section: all the rest
run = 'move-node-to-workspace 4'
